# --------------------------------------------------------------- 
# Licensed Materials - Property of IBM                            
# 5724-S84                                                        
# (C) Copyright IBM Corp. 2008       All Rights Reserved          
# US Government Users Restricted Rights - Use, duplication or     
# disclosure restricted by GSA ADP Schedule Contract with         
# IBM Corp.                                                       
# --------------------------------------------------------------- 
# PROLOG END TAG zYx                                              

########################################################################
#			Subdirectories
########################################################################

DIRS	:= 	simple_dma			\
		single_buffer			\
		single_buffer_list		\
		single_buffer_in_out		\
		single_buffer_list_in_out	\
		double_buffer			\
		double_buffer_list		\
		double_buffer_in_out		\
		double_buffer_list_in_out	\
		triple_buffer			\
		triple_buffer_in_out		\
		triple_buffer_list_in_out	\
		destructive_dma_list		

########################################################################
#			buildutils/make.footer
########################################################################

ifdef CELL_TOP
	include $(CELL_TOP)/buildutils/make.footer
else
	include /opt/cell/sdk/buildutils/make.footer
endif
